executors:
  node:
    docker:
      - image: cimg/node:13.11.0

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Npm Package Cache
      keys:
        - node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: "if [[ ! -z \"\" ]]; then\n  echo \"Running override package installation command:\"\n  \nelse\n  npm ci\nfi\n"

  save_cache: &save_cache
    save_cache:
      name: Save NPM package cache
      key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
      paths:
        - ~/.npm

version: 2

jobs:
  test:
    docker:
      - image: cimg/node:13.11.0
    steps:
      - checkout  
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Test
          command: npm run test
  build:
    docker:
      - image: cimg/node:13.11.0
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Build
          command: CI=false npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy:
    docker:
      - image: cimg/node:13.11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *restore_cache
      - <<: *install_node_modules
      - run: 
          name: Deploy to Netlify
          command: npm run netlify:deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
    - test
    - build:
        requires:
          - test
    - deploy: 
        requires:
          - build
